# Wordpress Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:latest
        env:
          - name: WORDPRESS_DB_USER 
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-user
          - name: WORDPRESS_DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-pass
          - name: WORDPRESS_DB_NAME 
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-db
          - name: WORDPRESS_DB_HOST 
            valueFrom:
              configMapKeyRef:
                name: mysql-cm
                key: mysql-url
        ports:
        - containerPort: 80
        volumeMounts:
          - name:  wordpress-persistent-storage
            mountPath:  /var/www/html
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name:  wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc 
---
# Wordpress Service
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress 
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001